---
name: Check

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  package:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/build-bun-package.yml@722ef29d1740604bd16be91fde520339d2cfadbb # master
