---
name: Check

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  package:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/build-bun-package.yml@dee521f49caa2626c8adeed2af4767887b2f202b # 20261009.1
    with:
      build-command: bun run test:package
