---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  general:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-general.yml@70421d48dd34dc6356326bc6a35386a0a3301561 # master

  skills:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-agent-skills.yml@70421d48dd34dc6356326bc6a35386a0a3301561 # master
    with:
      skill-roots: skills
