---
name: Publish

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  npm:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/publish-npm-package.yml@3d5608761e2468512c581fbe499737869c4c8f38 # master
    permissions:
      contents: read
      id-token: write

  jsr:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/publish-jsr-package.yml@3d5608761e2468512c581fbe499737869c4c8f38 # master
    permissions:
      contents: read
      id-token: write
