---
name: Publish

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  npm:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/publish-npm-package.yml@33ed693dee5840a8f43ed4df20e17cf2a967b620 # master
    permissions:
      contents: read
      id-token: write

  jsr:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/publish-jsr-package.yml@33ed693dee5840a8f43ed4df20e17cf2a967b620 # master
    permissions:
      contents: read
      id-token: write
