---
name: Publish

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  npm:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/publish-npm-package.yml@942a2e735c957787562e621d916fb6f78c9bb508 # 20261009.0
    permissions:
      contents: read
      id-token: write

  jsr:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/publish-jsr-package.yml@942a2e735c957787562e621d916fb6f78c9bb508 # 20261009.0
    permissions:
      contents: read
      id-token: write
