---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@60872ed566f5eede3ad98cd0fb23b1d64c292497 # master
    permissions:
      pull-requests: write
      contents: write
