---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@33ed693dee5840a8f43ed4df20e17cf2a967b620 # master
    permissions:
      pull-requests: write
      contents: write
